export const products = [
  {
    id: "1",
    name: "Produto 1",
    price: 99.99,
    image: (id: string) => `/images/products/product-${id}.jpg`,
    description: "Descrição do Produto 1",
    category: "Mais Vendidos",
  },
  {
    id: "2",
    name: "Produto 2",
    price: 149.99,
    image: (id: string) => `/images/products/product-${id}.jpg`,
    description: "Descrição do Produto 2",
    category: "Promoção",
  },
  {
    id: "3",
    name: "Produto 3",
    price: 199.99,
    image: (id: string) => `/images/products/product-${id}.jpg`,
    description: "Descrição do Produto 3",
    category: "Mais Vendidos",
  },
  {
    id: "4",
    name: "Produto 4",
    price: 249.99,
    image: (id: string) => `/images/products/product-${id}.jpg`,
    description: "Descrição do Produto 4",
    category: "Promoção",
  },
  {
    id: "5",
    name: "Produto 5",
    price: 59.99,
    image: (id: string) => `/images/products/product-${id}.jpg`,
    description: "Descrição do Produto 5",
    category: "Novidades",
  },
  {
    id: "6",
    name: "Produto 6",
    price: 119.99,
    image: (id: string) => `/images/products/product-${id}.jpg`,
    description: "Descrição do Produto 6",
    category: "Mais Vendidos",
  },
  {
    id: "7",
    name: "Produto 7",
    price: 89.99,
    image: (id: string) => `/images/products/product-${id}.jpg`,
    description: "Descrição do Produto 7",
    category: "Promoção",
  },
  {
    id: "8",
    name: "Produto 8",
    price: 159.99,
    image: (id: string) => `/images/products/product-${id}.jpg`,
    description: "Descrição do Produto 8",
    category: "Novidades",
  },
  {
    id: "9",
    name: "Produto 9",
    price: 129.99,
    image: (id: string) => `/images/products/product-${id}.jpg`,
    description: "Descrição do Produto 9",
    category: "Mais Vendidos",
  },
  {
    id: "10",
    name: "Produto 10",
    price: 179.99,
    image: (id: string) => `/images/products/product-${id}.jpg`,
    description: "Descrição do Produto 10",
    category: "Promoção",
  },
  {
    id: "11",
    name: "Produto 11",
    price: 199.99,
    image: (id: string) => `/images/products/product-${id}.jpg`,
    description: "Descrição do Produto 11",
    category: "Novidades",
  },
  {
    id: "12",
    name: "Produto 12",
    price: 159.99,
    image: (id: string) => `/images/products/product-${id}.jpg`,
    description: "Descrição do Produto 12",
    category: "Mais Vendidos",
  },
  {
    id: "13",
    name: "Produto 13",
    price: 109.99,
    image: (id: string) => `/images/products/product-${id}.jpg`,
    description: "Descrição do Produto 13",
    category: "Promoção",
  },
  {
    id: "14",
    name: "Produto 14",
    price: 139.99,
    image: (id: string) => `/images/products/product-${id}.jpg`,
    description: "Descrição do Produto 14",
    category: "Mais Vendidos",
  },
  {
    id: "15",
    name: "Produto 15",
    price: 169.99,
    image: (id: string) => `/images/products/product-${id}.jpg`,
    description: "Descrição do Produto 15",
    category: "Promoção",
  },
  {
    id: "16",
    name: "Produto 16",
    price: 219.99,
    image: (id: string) => `/images/products/product-${id}.jpg`,
    description: "Descrição do Produto 16",
    category: "Novidades",
  },
  {
    id: "17",
    name: "Produto 17",
    price: 249.99,
    image: (id: string) => `/images/products/product-${id}.jpg`,
    description: "Descrição do Produto 17",
    category: "Mais Vendidos",
  },
  {
    id: "18",
    name: "Produto 18",
    price: 89.99,
    image: (id: string) => `/images/products/product-${id}.jpg`,
    description: "Descrição do Produto 18",
    category: "Promoção",
  },
  {
    id: "19",
    name: "Produto 19",
    price: 299.99,
    image: (id: string) => `/images/products/product-${id}.jpg`,
    description: "Descrição do Produto 19",
    category: "Mais Vendidos",
  },
  {
    id: "20",
    name: "Produto 20",
    price: 79.99,
    image: (id: string) => `/images/products/product-${id}.jpg`,
    description: "Descrição do Produto 20",
    category: "Novidades",
  },
];
